"""Data Model 1.0

Revision ID: 71b0d65dc1b9
Revises: 
Create Date: 2020-05-24 17:50:42.672213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71b0d65dc1b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absence_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('absence_category', sa.String(length=50), nullable=True),
    sa.Column('absence_category_description', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absence_category_absence_category'), 'absence_category', ['absence_category'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('mgrid', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=1), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('lastseen', sa.DateTime(), nullable=True),
    sa.Column('aboutme', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['mgrid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_surname'), 'users', ['surname'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('absences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('absence_category_id', sa.Integer(), nullable=True),
    sa.Column('ts_absence_start', sa.DateTime(), nullable=True),
    sa.Column('ts_absence_end', sa.DateTime(), nullable=True),
    sa.Column('ts_requested', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['absence_category_id'], ['absence_category.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_absences_absence_category_id'), 'absences', ['absence_category_id'], unique=False)
    op.create_index(op.f('ix_absences_ts_absence_start'), 'absences', ['ts_absence_start'], unique=False)
    op.create_index(op.f('ix_absences_ts_requested'), 'absences', ['ts_requested'], unique=False)
    op.create_index(op.f('ix_absences_userid'), 'absences', ['userid'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_absences_userid'), table_name='absences')
    op.drop_index(op.f('ix_absences_ts_requested'), table_name='absences')
    op.drop_index(op.f('ix_absences_ts_absence_start'), table_name='absences')
    op.drop_index(op.f('ix_absences_absence_category_id'), table_name='absences')
    op.drop_table('absences')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_surname'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_absence_category_absence_category'), table_name='absence_category')
    op.drop_table('absence_category')
    # ### end Alembic commands ###
